name: moshi-env
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - appdirs=1.4.3
  - arrow=0.15.2
  - asn1crypto=1.2.0
  - attrs=19.3.0
  - binaryornot=0.4.4
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2019.10.16
  - certifi=2019.9.11
  - cffi=1.13.1
  - chardet=3.0.4
  - click=7.0
  - cookiecutter=1.6.0
  - cryptography=2.7
  - datrie=0.8
  - docutils=0.15.2
  - future=0.18.1
  - gitdb2=2.0.6
  - gitpython=3.0.4
  - idna=2.8
  - importlib_metadata=0.23
  - intel-openmp=2019.4
  - jinja2=2.10.3
  - jinja2-time=0.2.0
  - jsonschema=3.1.1
  - libcxx=9.0.0
  - libffi=3.2.1
  - libgfortran
  - markupsafe=1.1.1
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.14
  - mkl_random=1.1.0
  - more-itertools=7.2.0
  - ncurses=6.1
  - numpy=1.17.2
  - numpy-base=1.17.2
  - openssl=1.1.1
  - pandas=0.25.2
  - pbr=5.4.3
  - pip=19.3.1
  - plotly=4.2.1
  - poyo=0.5.0
  - psutil=5.6.3
  - pycparser=2.19
  - pyopenssl=19.0.0
  - pysocks=1.7.1
  - python=3.7.3
  - python-dateutil=2.8.0
  - pytz=2019.3
  - pyyaml=5.1.2
  - readline=8.0
  - requests=2.22.0
  - retrying=1.3.3
  - scipy=1.3.1
  - setuptools=41.6.0
  - six=1.12.0
  - smmap2=2.0.5
  - sqlite=3.30.1
  - tk=8.6.9
  - urllib3=1.25.6
  - wheel=0.33.6
  - whichcraft=0.6.1
  - wrapt=1.11.2
  - xz=5.2.4
  - yaml=0.1.7
  - zipp=0.6.0
  - zlib=1.2.11
  - pip:
    - configargparse==0.15.1
    - pyrsistent==0.15.5
    - ratelimiter==1.2.0.post0
    - snakemake==5.7.1
prefix: /usr/local/Caskroom/miniconda/base/envs/moshi-env

