name: rapids202007
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0
  - appdirs=1.4.3
  - arrow=0.15.2
  - asn1crypto=1.2.0
  - astropy=4.0.1.post1
  - attrs=19.3.0
  - binaryornot=0.4.4
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2020.6.20
  - certifi=2020.6.20
  - cffi=1.13.1
  - chardet=3.0.4
  - click=7.0
  - cookiecutter=1.6.0
  - cryptography=2.7
  - datrie=0.8.2
  - docutils=0.15.2
  - future=0.18.1
  - gitdb2=2.0.6
  - gitpython=3.0.4
  - idna=2.8
  - imbalanced-learn=0.6.2
  - importlib_metadata=0.23
  - intel-openmp=2019.4
  - jinja2=2.10.3
  - jinja2-time=0.2.0
  - joblib=0.16.0
  - jsonschema=3.1.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcxx=9.0.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran
  - liblapack=3.8.0
  - libxgboost=0.90
  - lightgbm=2.3.0
  - llvm-openmp=10.0.0
  - markupsafe=1.1.1
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.14
  - mkl_random=1.1.0
  - more-itertools=7.2.0
  - ncurses=6.1
  - numpy=1.17.2
  - numpy-base=1.17.2
  - openssl=1.1.1g
  - pandas=0.25.2
  - pbr=5.4.3
  - pip=19.3.1
  - plotly=4.2.1
  - poyo=0.5.0
  - psutil=5.6.3
  - py-xgboost=0.90
  - pycparser=2.19
  - pyopenssl=19.0.0
  - pysocks=1.7.1
  - python=3.7.3
  - python-dateutil=2.8.0
  - python_abi=3.7
  - pytz=2019.3
  - pyyaml=5.1.2
  - readline=8.0
  - requests=2.22.0
  - retrying=1.3.3
  - scikit-learn=0.22.1
  - scipy=1.3.1
  - setuptools=41.6.0
  - six=1.12.0
  - smmap2=2.0.5
  - sqlite=3.30.1
  - tk=8.6.9
  - urllib3=1.25.6
  - wheel=0.33.6
  - whichcraft=0.6.1
  - wrapt=1.11.2
  - xgboost=0.90
  - xz=5.2.4
  - yaml=0.1.7
  - zipp=0.6.0
  - zlib=1.2.11
  - pip:
    - configargparse==0.15.1
    - decorator==4.4.2
    - ipython-genutils==0.2.0
    - jupyter-core==4.6.3
    - nbformat==5.0.7
    - pyrsistent==0.15.5
    - ratelimiter==1.2.0.post0
    - snakemake==5.20.1
    - toposort==1.5
    - traitlets==4.3.3
prefix: /usr/local/Caskroom/miniconda/base/envs/rapids202007

