site_name: RAPIDS
site_url: https://www.rapids.science/
markdown_extensions:
    - toc:
        permalink: True
    - admonition
    - smarty
    - wikilinks
    - codehilite:
        linenums: True
    # - urlize # requires: pip install git+https://github.com/r0wb0t/markdown-urlize.git
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.snippets:
        check_paths: True
    - pymdownx.tabbed
    - pymdownx.tasklist:
        custom_checkbox: True
    - pymdownx.tilde
    - attr_list
    - pymdownx.keys
    - def_list
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/julio_ui'
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

repo_name: 'carissalow/rapids'
repo_url: 'https://github.com/carissalow/rapids'
copyright: 'Released under AGPL'
theme:
  name: material
  custom_dir: docs/overrides
  logo: img/logo.png
  favicon: img/logo.png
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  features:
    - navigation.sections
    - search.suggest
    - search.highlight
extra_css:
    - stylesheets/extra.css
nav:
  - Home: 'index.md'
  - Setup:
    - Overview: setup/overview.md
    - Minimal Example: workflow-examples/minimal.md
    - Installation: 'setup/installation.md'
    - Configuration: setup/configuration.md
    - Execution: setup/execution.md
    - Citation: citation.md
  - Data Streams:
      - Introduction: datastreams/data-streams-introduction.md
      - Phone:
        - aware_mysql: datastreams/aware-mysql.md
        - aware_csv: datastreams/aware-csv.md
        - aware_influxdb (beta): datastreams/aware-influxdb.md
        - Mandatory Phone Format: datastreams/mandatory-phone-format.md
      - Fitbit:
        - fitbitjson_mysql: datastreams/fitbitjson-mysql.md
        - fitbitjson_csv: datastreams/fitbitjson-csv.md
        - fitbitparsed_mysql: datastreams/fitbitparsed-mysql.md
        - fitbitparsed_csv: datastreams/fitbitparsed-csv.md
        - Mandatory Fitbit Format: datastreams/mandatory-fitbit-format.md
      - Empatica:
        - empatica_zip: datastreams/empatica-zip.md
        - Mandatory Empatica Format: datastreams/mandatory-empatica-format.md
      - Add New Data Streams: datastreams/add-new-data-streams.md
  - Behavioral Features:
      - Introduction: features/feature-introduction.md
      - Phone:
        - Phone Accelerometer: features/phone-accelerometer.md
        - Phone Activity Recognition: features/phone-activity-recognition.md
        - Phone Applications Crashes: features/phone-applications-crashes.md
        - Phone Applications Foreground: features/phone-applications-foreground.md
        - Phone Applications Notifications: features/phone-applications-notifications.md
        - Phone Battery: features/phone-battery.md
        - Phone Bluetooth: features/phone-bluetooth.md
        - Phone Calls: features/phone-calls.md
        - Phone Conversation: features/phone-conversation.md
        - Phone Data Yield: features/phone-data-yield.md
        - Phone Keyboard: features/phone-keyboard.md
        - Phone Light: features/phone-light.md
        - Phone Locations: features/phone-locations.md
        - Phone Log: features/phone-log.md
        - Phone Messages: features/phone-messages.md
        - Phone Screen: features/phone-screen.md
        - Phone WiFI Connected: features/phone-wifi-connected.md
        - Phone WiFI Visible: features/phone-wifi-visible.md
      - Fitbit:
        - Fitbit Data Yield: features/fitbit-data-yield.md
        - Fitbit Heart Rate Summary: features/fitbit-heartrate-summary.md
        - Fitbit Heart Rate Intraday: features/fitbit-heartrate-intraday.md
        - Fitbit Sleep Summary: features/fitbit-sleep-summary.md
        - Fitbit Sleep Intraday: features/fitbit-sleep-intraday.md
        - Fitbit Steps Summary: features/fitbit-steps-summary.md
        - Fitbit Steps Intraday: features/fitbit-steps-intraday.md
      - Empatica:
        - Empatica Accelerometer: features/empatica-accelerometer.md
        - Empatica Heart Rate: features/empatica-heartrate.md
        - Empatica Temperature: features/empatica-temperature.md
        - Empatica Electrodermal Activity: features/empatica-electrodermal-activity.md
        - Empatica Blood Volume Pulse: features/empatica-blood-volume-pulse.md
        - Empatica Inter Beat Interval: features/empatica-inter-beat-interval.md
        - Empatica Tags: features/empatica-tags.md
      - Add New Features: features/add-new-features.md
  - Visualizations:
    - Data Quality: visualizations/data-quality-visualizations.md
    - Features: visualizations/feature-visualizations.md
  - Analysis Workflows:
    - Complete Example: workflow-examples/analysis.md
  - Developers:
    - Git Flow: developers/git-flow.md
    - Remote Support: developers/remote-support.md
    - Virtual Environments: developers/virtual-environments.md
    - Documentation: developers/documentation.md
    - Testing: developers/testing.md
    - Test cases: developers/test-cases.md
    - Validation schema of config.yaml: developers/validation-schema-config.md
  - Others:
    - Migrating from an old version: migrating-from-old-versions.md
    - Code of Conduct: code_of_conduct.md
    - Common Errors: common-errors.md
    - Team: team.md
    - Change Log: change-log.md
